import type { DictumModel } from "./types";

/** Static mirror of the Rust registry — used in web mode where `get_models` is unavailable. */
export const MODEL_CATALOG: DictumModel[] = [
  {
    id: "tiny",
    label: "Whisper Tiny",
    kind: "local",
    blurb: "Fastest on-device option. Quick notes and light machines.",
    speed: 5,
    accuracy: 2,
    featured: true,
    file: "ggml-tiny.en.bin",
    size: "~75 MB",
    provider: null,
  },
  {
    id: "base",
    label: "Whisper Base",
    kind: "local",
    blurb: "Balanced speed and accuracy. The default for most users.",
    speed: 4,
    accuracy: 3,
    featured: true,
    file: "ggml-base.en.bin",
    size: "~142 MB",
    provider: null,
  },
  {
    id: "small",
    label: "Whisper Small",
    kind: "local",
    blurb: "Strong accuracy with Metal acceleration. Great daily driver.",
    speed: 3,
    accuracy: 4,
    featured: true,
    file: "ggml-small.en.bin",
    size: "~466 MB",
    provider: null,
  },
  {
    id: "medium",
    label: "Whisper Medium",
    kind: "local",
    blurb: "Professional-grade local accuracy. Heavier download.",
    speed: 2,
    accuracy: 4,
    featured: false,
    file: "ggml-medium.en.bin",
    size: "~1.5 GB",
    provider: null,
  },
  {
    id: "large-v3-turbo",
    label: "Whisper Large v3 Turbo",
    kind: "local",
    blurb: "Near-large accuracy at ~4× speed. Best local sweet spot.",
    speed: 3,
    accuracy: 5,
    featured: false,
    file: "ggml-large-v3-turbo.bin",
    size: "~1.6 GB",
    provider: null,
  },
  {
    id: "large-v3",
    label: "Whisper Large v3",
    kind: "local",
    blurb: "Maximum local accuracy. Multilingual and demanding.",
    speed: 1,
    accuracy: 5,
    featured: false,
    file: "ggml-large-v3.bin",
    size: "~2.9 GB",
    provider: null,
  },
  {
    id: "tiny-multilingual",
    label: "Whisper Tiny (Multilingual)",
    kind: "local",
    blurb: "Compact model with broad language support.",
    speed: 5,
    accuracy: 2,
    featured: false,
    file: "ggml-tiny.bin",
    size: "~75 MB",
    provider: null,
  },
  {
    id: "base-multilingual",
    label: "Whisper Base (Multilingual)",
    kind: "local",
    blurb: "Lightweight multilingual transcription.",
    speed: 4,
    accuracy: 3,
    featured: false,
    file: "ggml-base.bin",
    size: "~142 MB",
    provider: null,
  },
  {
    id: "openai-whisper-1",
    label: "OpenAI Whisper",
    kind: "cloud",
    blurb: "Industry-standard cloud transcription via OpenAI.",
    speed: 4,
    accuracy: 4,
    featured: false,
    provider: "openai",
  },
  {
    id: "openai-gpt-4o-transcribe",
    label: "GPT-4o Transcribe",
    kind: "cloud",
    blurb: "OpenAI's latest speech model with strong formatting.",
    speed: 3,
    accuracy: 5,
    featured: false,
    provider: "openai",
  },
  {
    id: "openai-gpt-4o-mini-transcribe",
    label: "GPT-4o Mini Transcribe",
    kind: "cloud",
    blurb: "Lower-cost OpenAI transcription with solid accuracy.",
    speed: 5,
    accuracy: 4,
    featured: false,
    provider: "openai",
  },
  {
    id: "deepgram-nova-3",
    label: "Deepgram Nova-3",
    kind: "cloud",
    blurb: "Fast streaming cloud STT tuned for real-time use.",
    speed: 5,
    accuracy: 4,
    featured: false,
    provider: "deepgram",
  },
  {
    id: "assemblyai-universal",
    label: "AssemblyAI Universal",
    kind: "cloud",
    blurb: "Robust cloud model with strong punctuation.",
    speed: 4,
    accuracy: 4,
    featured: false,
    provider: "assemblyai",
  },
  {
    id: "groq-whisper-large-v3",
    label: "Groq Whisper Large v3",
    kind: "cloud",
    blurb: "Whisper Large v3 on Groq's ultra-low-latency hardware.",
    speed: 5,
    accuracy: 5,
    featured: false,
    provider: "groq",
  },
  {
    id: "google-chirp-2",
    label: "Google Chirp 2",
    kind: "cloud",
    blurb: "Google Cloud speech model with wide language coverage.",
    speed: 3,
    accuracy: 5,
    featured: false,
    provider: "google",
  },
];

export const PROVIDER_LABELS: Record<string, string> = {
  openai: "OpenAI",
  deepgram: "Deepgram",
  assemblyai: "AssemblyAI",
  groq: "Groq",
  google: "Google Cloud",
};
